name: validate
on:
  pull_request:
  push:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ runner.os }}-${{ matrix.node }}
      - name: validate presets
        run: |
          for file in *.json; do
            echo --- $file ---
            RENOVATE_CONFIG_FILE=$file npx -p renovate -c renovate-config-validator
          done
      - name: validate usages
        run: |
          for file in test/*.json; do
            echo --- $file ---
            RENOVATE_CONFIG_FILE=$file npx -p renovate -c renovate-config-validator
          done
